apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize
  - namespace.yaml

images:
  - name: shivani2330/frontend:latest
    newName: shivani2330/frontend:latest
    newTag: v1

namespace: local