apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./coit-frontend-deployment.yaml
  - ./service-coit-frontend-lb.yaml
  - ./frontend-pvc.yaml
images:
  - name: shivani2330/frontend:latest
    newTag: 4.0.0
namePrefix: frontend-
nameSuffix: -development
commonLabels:
  customer: customer1
  environment: development
  myapp: coit-frontend
  app: coitfrontend
labels:
  - pairs:
      location: us-west